"""v3_5_sprint5_migration

Revision ID: b78b8156ab79
Revises: 2ef3cb52a123
Create Date: 2026-07-11 04:03:35.645014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b78b8156ab79'
down_revision: Union[str, None] = '2ef3cb52a123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys'))
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=True)

    op.create_table('webhook_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_events'))
    )
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_events_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_events_status'), ['status'], unique=False)

    op.create_table('user_devices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('device_token', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_devices_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_devices')),
    sa.UniqueConstraint('device_token', name=op.f('uq_user_devices_device_token'))
    )
    with op.batch_alter_table('user_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_devices_user_id'), ['user_id'], unique=False)

    op.create_table('user_locations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('battery_level', sa.Integer(), nullable=True),
    sa.Column('network_type', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_locations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_locations'))
    )
    with op.batch_alter_table('user_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_locations_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_locations_user_id'), ['user_id'], unique=False)

    op.create_table('matching_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lot_id', sa.Uuid(), nullable=False),
    sa.Column('collector_id', sa.Uuid(), nullable=False),
    sa.Column('distance_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('reliability_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('capacity_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('availability_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('experience_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('final_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('decision_explanation', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collector_id'], ['users.id'], name=op.f('fk_matching_decisions_collector_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lot_id'], ['waste_lots.id'], name=op.f('fk_matching_decisions_lot_id_waste_lots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matching_decisions'))
    )
    with op.batch_alter_table('matching_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matching_decisions_collector_id'), ['collector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matching_decisions_lot_id'), ['lot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matching_decisions_selected'), ['selected'], unique=False)

    with op.batch_alter_table('device_tokens', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_encrypted', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('phone_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('encryption_key_version', sa.Integer(), nullable=True))
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_index('ix_users_phone')
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_phone_hash'), ['phone_hash'], unique=True)

    with op.batch_alter_table('verification_evidences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_hash', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('uploaded_by_id', sa.Uuid(), nullable=False))
        batch_op.create_index(batch_op.f('ix_verification_evidences_file_hash'), ['file_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_verification_evidences_uploaded_by_id'), ['uploaded_by_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_verification_evidences_uploaded_by_id_users'), 'users', ['uploaded_by_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_evidences', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_verification_evidences_uploaded_by_id_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_verification_evidences_uploaded_by_id'))
        batch_op.drop_index(batch_op.f('ix_verification_evidences_file_hash'))
        batch_op.drop_column('uploaded_by_id')
        batch_op.drop_column('file_hash')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone_hash'))
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.create_index('ix_users_phone', ['phone'], unique=1)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('encryption_key_version')
        batch_op.drop_column('phone_hash')
        batch_op.drop_column('phone_encrypted')

    with op.batch_alter_table('device_tokens', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('matching_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matching_decisions_selected'))
        batch_op.drop_index(batch_op.f('ix_matching_decisions_lot_id'))
        batch_op.drop_index(batch_op.f('ix_matching_decisions_collector_id'))

    op.drop_table('matching_decisions')
    with op.batch_alter_table('user_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_locations_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_locations_location'))

    op.drop_table('user_locations')
    with op.batch_alter_table('user_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_devices_user_id'))

    op.drop_table('user_devices')
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_events_status'))
        batch_op.drop_index(batch_op.f('ix_webhook_events_provider'))

    op.drop_table('webhook_events')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))
        batch_op.drop_index(batch_op.f('ix_api_keys_active'))

    op.drop_table('api_keys')
    # ### end Alembic commands ###
