"""Add illegal dump reports

Revision ID: bef709e68263
Revises: 13cf4de466b7
Create Date: 2026-07-11 01:34:44.633216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bef709e68263'
down_revision: Union[str, None] = '13cf4de466b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('illegal_dump_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reporter_id', sa.Uuid(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=False),
    sa.Column('estimated_volume_m3', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', 'CLEANED', name='reportstatus'), nullable=False),
    sa.Column('ai_confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('ai_tags', sa.JSON(), nullable=True),
    sa.Column('reward_awarded', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_illegal_dump_reports_reporter_id'), 'illegal_dump_reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_illegal_dump_reports_status'), 'illegal_dump_reports', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_illegal_dump_reports_status'), table_name='illegal_dump_reports')
    op.drop_index(op.f('ix_illegal_dump_reports_reporter_id'), table_name='illegal_dump_reports')
    op.drop_table('illegal_dump_reports')
    # ### end Alembic commands ###
