"""init schema

Revision ID: d352e6418378
Revises: 
Create Date: 2026-07-08 11:40:59.193772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd352e6418378'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('PRODUCTEUR', 'COLLECTEUR', 'INDUSTRIEL', 'MAIRIE', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('otp_hash', sa.String(length=255), nullable=True),
    sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reset_token_hash', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('rewards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('total_kg_recycled', sa.Float(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rewards_user_id'), 'rewards', ['user_id'], unique=True)
    op.create_table('waste_lots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('producer_id', sa.Uuid(), nullable=False),
    sa.Column('collector_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.Enum('PLASTIQUE', 'CARTON', 'METAL', 'VERRE', 'ORGANIQUE', 'ELECTRONIQUE', 'AUTRE', name='wastecategory'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('status', sa.Enum('DISPONIBLE', 'RESERVE', 'COLLECTE', 'ANNULE', name='lotstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['collector_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['producer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waste_lots_collector_id'), 'waste_lots', ['collector_id'], unique=False)
    op.create_index(op.f('ix_waste_lots_producer_id'), 'waste_lots', ['producer_id'], unique=False)
    op.create_index(op.f('ix_waste_lots_status'), 'waste_lots', ['status'], unique=False)
    op.create_table('collections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('waste_lot_id', sa.Uuid(), nullable=False),
    sa.Column('collector_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('RESERVEE', 'EN_ROUTE', 'VALIDEE', 'ANNULEE', name='collectionstatus'), nullable=False),
    sa.Column('validation_code_hash', sa.String(length=255), nullable=True),
    sa.Column('actual_weight_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('reserved_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['collector_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['waste_lot_id'], ['waste_lots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_collector_id'), 'collections', ['collector_id'], unique=False)
    op.create_index(op.f('ix_collections_waste_lot_id'), 'collections', ['waste_lot_id'], unique=True)
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.Column('producer_id', sa.Uuid(), nullable=False),
    sa.Column('collector_id', sa.Uuid(), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('MOBILE_MONEY', 'ESPECES', 'VIREMENT', name='paymentmethod'), nullable=False),
    sa.Column('status', sa.Enum('EN_ATTENTE', 'PAYEE', 'ECHOUEE', 'REMBOURSEE', name='transactionstatus'), nullable=False),
    sa.Column('external_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collector_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['producer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_collection_id'), 'transactions', ['collection_id'], unique=True)
    op.create_index(op.f('ix_transactions_collector_id'), 'transactions', ['collector_id'], unique=False)
    op.create_index(op.f('ix_transactions_producer_id'), 'transactions', ['producer_id'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_producer_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_collector_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_collection_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_collections_waste_lot_id'), table_name='collections')
    op.drop_index(op.f('ix_collections_collector_id'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_waste_lots_status'), table_name='waste_lots')
    op.drop_index(op.f('ix_waste_lots_producer_id'), table_name='waste_lots')
    op.drop_index(op.f('ix_waste_lots_collector_id'), table_name='waste_lots')
    op.drop_table('waste_lots')
    op.drop_index(op.f('ix_rewards_user_id'), table_name='rewards')
    op.drop_table('rewards')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
